version: '3.7'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        container_name: pokedex_es
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
            - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:7.2.0
        container_name: pokedex_kibana
        volumes:
            - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge